### ISSUE TITLE
Undefined method each for type Yaml::Any

### ISSUE THREAD

**Issue by nobilik** [philnash/envyable.cr#1]
Hi, with Crystal 26.1 it doesn't work any more. Could you please fix it? By me `to_h` in loader will fix it.

**Comment by philnash** [comment]
Thanks for raising this. I'll take a look.

**Comment by philnash** [comment]
Updated and released as 1.0.1.

**Comment by nobilik** [comment]
I'm sorry I mean `as_h`

**Comment by philnash** [comment]
No worries, I worked that out and we’re all set! 👍
